version: "3.7"

services:

  mercury-homepage:
      image: "aditazz/mercury-landing:${IMAGE_TAG}"
      deploy:
        replicas: 2
        update_config:
          parallelism: 1
          delay: 10s
        restart_policy:
          condition: on-failure
        labels:
          - "traefik.enable=true"

          - "traefik.http.routers.mercury-homepage_http.rule=Host(`$HOSTNAME`) || Host(`www.$HOSTNAME`)"
          - "traefik.http.routers.mercury-homepage_http.middlewares=https_redirect"
          
          - "traefik.http.routers.mercury-homepage_https.rule=Host(`$HOSTNAME`) || Host(`www.$HOSTNAME`)"
          - "traefik.http.routers.mercury-homepage_https.tls.certresolver=le"
          - "traefik.http.routers.mercury-homepage_https.middlewares=wwwredirect"

          - "traefik.http.services.mercury-homepage.loadbalancer.server.port=80"

          - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
          - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"

          - "traefik.http.middlewares.wwwredirect.redirectregex.regex=^https://www.${HOSTNAME}/(.*)"
          - "traefik.http.middlewares.wwwredirect.redirectregex.replacement=https://${HOSTNAME}/$${1}"

      networks:
        - traefik_default


networks:
  traefik_default:
    external: true
